name = "TreeAMR"
uuid = "91bc416d-811c-44c1-9bc4-b9c8bbdbbd08"
version = "0.1.5"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[weakdeps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
TreeAMRHDF5Ext = "HDF5"
TreeAMRMPIExt = "MPI"

[compat]
CRC32c = "1"
HDF5 = "0.17"
KernelAbstractions = "0.9.42, 1"
MPI = "0.20"
julia = "1.11"
