name = "TreeAMR"
uuid = "91bc416d-811c-44c1-9bc4-b9c8bbdbbd08"
version = "0.2.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
TreeAMRMPIExt = "MPI"

[compat]
KernelAbstractions = "0.9.42, 1"
MPI = "0.20"
julia = "1.11"
